// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using librarymanagement.Models;

#nullable disable

namespace librarymanagement.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20250224074118_AddFineRecordsTable")]
    partial class AddFineRecordsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("librarymanagement.Models.FineRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("bookname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("fineamount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("finedate")
                        .HasColumnType("datetime2");

                    b.Property<int>("studentid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FineRecords");
                });

            modelBuilder.Entity("librarymanagement.Models.IssueBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("authorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("duedate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("issuedate")
                        .HasColumnType("datetime2");

                    b.Property<int>("studentid")
                        .HasColumnType("int");

                    b.Property<string>("studentname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IssuedBooks");
                });

            modelBuilder.Entity("librarymanagement.Models.ReturnBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("authorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("fineamount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("returndate")
                        .HasColumnType("datetime2");

                    b.Property<int>("studentid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReturnedBooks");
                });

            modelBuilder.Entity("librarymanagement.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("contactnumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("studentid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
